name: zd_market
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  badges: ^3.1.2
  card_swiper: ^3.0.1
  cloud_firestore: ^4.16.1
  cupertino_icons: ^1.0.6
  fancy_shimmer_image: ^2.0.3
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_stripe: ^10.1.1
  fluttertoast: ^8.2.5
  google_sign_in: ^6.2.1
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/cat/
    - assets/images/landing/
    - assets/images/offres/
